# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/qubka/Desktop/Vulkan

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/qubka/Desktop/Vulkan

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/qubka/Desktop/Vulkan/CMakeFiles /home/qubka/Desktop/Vulkan//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/qubka/Desktop/Vulkan/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Engine

# Build rule for target.
Engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Engine
.PHONY : Engine

# fast build rule for target.
Engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/build
.PHONY : Engine/fast

# target to build an object file
cmake_pch.hxx.gch:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/cmake_pch.hxx.gch
.PHONY : cmake_pch.hxx.gch

# target to preprocess a source file
cmake_pch.hxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/cmake_pch.hxx.i
.PHONY : cmake_pch.hxx.i

# target to generate assembly for a file
cmake_pch.hxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/cmake_pch.hxx.s
.PHONY : cmake_pch.hxx.s

src/Game.o: src/Game.cpp.o
.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i
.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s
.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/graphics/Device.o: src/graphics/Device.cpp.o
.PHONY : src/graphics/Device.o

# target to build an object file
src/graphics/Device.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/graphics/Device.cpp.o
.PHONY : src/graphics/Device.cpp.o

src/graphics/Device.i: src/graphics/Device.cpp.i
.PHONY : src/graphics/Device.i

# target to preprocess a source file
src/graphics/Device.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/graphics/Device.cpp.i
.PHONY : src/graphics/Device.cpp.i

src/graphics/Device.s: src/graphics/Device.cpp.s
.PHONY : src/graphics/Device.s

# target to generate assembly for a file
src/graphics/Device.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/graphics/Device.cpp.s
.PHONY : src/graphics/Device.cpp.s

src/graphics/Input.o: src/graphics/Input.cpp.o
.PHONY : src/graphics/Input.o

# target to build an object file
src/graphics/Input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/graphics/Input.cpp.o
.PHONY : src/graphics/Input.cpp.o

src/graphics/Input.i: src/graphics/Input.cpp.i
.PHONY : src/graphics/Input.i

# target to preprocess a source file
src/graphics/Input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/graphics/Input.cpp.i
.PHONY : src/graphics/Input.cpp.i

src/graphics/Input.s: src/graphics/Input.cpp.s
.PHONY : src/graphics/Input.s

# target to generate assembly for a file
src/graphics/Input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/graphics/Input.cpp.s
.PHONY : src/graphics/Input.cpp.s

src/graphics/Mesh.o: src/graphics/Mesh.cpp.o
.PHONY : src/graphics/Mesh.o

# target to build an object file
src/graphics/Mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/graphics/Mesh.cpp.o
.PHONY : src/graphics/Mesh.cpp.o

src/graphics/Mesh.i: src/graphics/Mesh.cpp.i
.PHONY : src/graphics/Mesh.i

# target to preprocess a source file
src/graphics/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/graphics/Mesh.cpp.i
.PHONY : src/graphics/Mesh.cpp.i

src/graphics/Mesh.s: src/graphics/Mesh.cpp.s
.PHONY : src/graphics/Mesh.s

# target to generate assembly for a file
src/graphics/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/graphics/Mesh.cpp.s
.PHONY : src/graphics/Mesh.cpp.s

src/graphics/Pipeline.o: src/graphics/Pipeline.cpp.o
.PHONY : src/graphics/Pipeline.o

# target to build an object file
src/graphics/Pipeline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/graphics/Pipeline.cpp.o
.PHONY : src/graphics/Pipeline.cpp.o

src/graphics/Pipeline.i: src/graphics/Pipeline.cpp.i
.PHONY : src/graphics/Pipeline.i

# target to preprocess a source file
src/graphics/Pipeline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/graphics/Pipeline.cpp.i
.PHONY : src/graphics/Pipeline.cpp.i

src/graphics/Pipeline.s: src/graphics/Pipeline.cpp.s
.PHONY : src/graphics/Pipeline.s

# target to generate assembly for a file
src/graphics/Pipeline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/graphics/Pipeline.cpp.s
.PHONY : src/graphics/Pipeline.cpp.s

src/graphics/Renderer.o: src/graphics/Renderer.cpp.o
.PHONY : src/graphics/Renderer.o

# target to build an object file
src/graphics/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/graphics/Renderer.cpp.o
.PHONY : src/graphics/Renderer.cpp.o

src/graphics/Renderer.i: src/graphics/Renderer.cpp.i
.PHONY : src/graphics/Renderer.i

# target to preprocess a source file
src/graphics/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/graphics/Renderer.cpp.i
.PHONY : src/graphics/Renderer.cpp.i

src/graphics/Renderer.s: src/graphics/Renderer.cpp.s
.PHONY : src/graphics/Renderer.s

# target to generate assembly for a file
src/graphics/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/graphics/Renderer.cpp.s
.PHONY : src/graphics/Renderer.cpp.s

src/graphics/SimpleRenderSystem.o: src/graphics/SimpleRenderSystem.cpp.o
.PHONY : src/graphics/SimpleRenderSystem.o

# target to build an object file
src/graphics/SimpleRenderSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/graphics/SimpleRenderSystem.cpp.o
.PHONY : src/graphics/SimpleRenderSystem.cpp.o

src/graphics/SimpleRenderSystem.i: src/graphics/SimpleRenderSystem.cpp.i
.PHONY : src/graphics/SimpleRenderSystem.i

# target to preprocess a source file
src/graphics/SimpleRenderSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/graphics/SimpleRenderSystem.cpp.i
.PHONY : src/graphics/SimpleRenderSystem.cpp.i

src/graphics/SimpleRenderSystem.s: src/graphics/SimpleRenderSystem.cpp.s
.PHONY : src/graphics/SimpleRenderSystem.s

# target to generate assembly for a file
src/graphics/SimpleRenderSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/graphics/SimpleRenderSystem.cpp.s
.PHONY : src/graphics/SimpleRenderSystem.cpp.s

src/graphics/SwapChain.o: src/graphics/SwapChain.cpp.o
.PHONY : src/graphics/SwapChain.o

# target to build an object file
src/graphics/SwapChain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/graphics/SwapChain.cpp.o
.PHONY : src/graphics/SwapChain.cpp.o

src/graphics/SwapChain.i: src/graphics/SwapChain.cpp.i
.PHONY : src/graphics/SwapChain.i

# target to preprocess a source file
src/graphics/SwapChain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/graphics/SwapChain.cpp.i
.PHONY : src/graphics/SwapChain.cpp.i

src/graphics/SwapChain.s: src/graphics/SwapChain.cpp.s
.PHONY : src/graphics/SwapChain.s

# target to generate assembly for a file
src/graphics/SwapChain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/graphics/SwapChain.cpp.s
.PHONY : src/graphics/SwapChain.cpp.s

src/graphics/Window.o: src/graphics/Window.cpp.o
.PHONY : src/graphics/Window.o

# target to build an object file
src/graphics/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/graphics/Window.cpp.o
.PHONY : src/graphics/Window.cpp.o

src/graphics/Window.i: src/graphics/Window.cpp.i
.PHONY : src/graphics/Window.i

# target to preprocess a source file
src/graphics/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/graphics/Window.cpp.i
.PHONY : src/graphics/Window.cpp.i

src/graphics/Window.s: src/graphics/Window.cpp.s
.PHONY : src/graphics/Window.s

# target to generate assembly for a file
src/graphics/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/graphics/Window.cpp.s
.PHONY : src/graphics/Window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Engine"
	@echo "... cmake_pch.hxx.gch"
	@echo "... cmake_pch.hxx.i"
	@echo "... cmake_pch.hxx.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/graphics/Device.o"
	@echo "... src/graphics/Device.i"
	@echo "... src/graphics/Device.s"
	@echo "... src/graphics/Input.o"
	@echo "... src/graphics/Input.i"
	@echo "... src/graphics/Input.s"
	@echo "... src/graphics/Mesh.o"
	@echo "... src/graphics/Mesh.i"
	@echo "... src/graphics/Mesh.s"
	@echo "... src/graphics/Pipeline.o"
	@echo "... src/graphics/Pipeline.i"
	@echo "... src/graphics/Pipeline.s"
	@echo "... src/graphics/Renderer.o"
	@echo "... src/graphics/Renderer.i"
	@echo "... src/graphics/Renderer.s"
	@echo "... src/graphics/SimpleRenderSystem.o"
	@echo "... src/graphics/SimpleRenderSystem.i"
	@echo "... src/graphics/SimpleRenderSystem.s"
	@echo "... src/graphics/SwapChain.o"
	@echo "... src/graphics/SwapChain.i"
	@echo "... src/graphics/SwapChain.s"
	@echo "... src/graphics/Window.o"
	@echo "... src/graphics/Window.i"
	@echo "... src/graphics/Window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

